development:
  adapter: postgresql
  encoding: unicode
  database: schedule_dev

test:
  adapter: postgresql
  encoding: unicode
  database: schedule_test

production:
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['DB_NAME'] %>
  pool: 5
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASS'] %>
  host: <%= ENV['DB_HOST'] %>